---
- hosts: all
  become: yes
  vars_files:
  - vars
  tasks:

  - name: "Set timezone to Europe/Madrid"
    timezone:
      name: Europe/Madrid
  
  - name: Desactivando partición de swap
    shell: swapoff -a

  - name: Eliminando swap de la tabla de particiones /etc/fstab
    replace:
     path: /etc/fstab
     regexp: '(^/.*swap*)'
     replace: '# \1'

  - name: Configuración de IP de los nodos
    lineinfile:
      dest: /etc/hosts
      regexp: '.*{{ item }}$'
      line: "{{ hostvars[item].ansible_host }} {{item}}"
      state: present
    when: hostvars[item].ansible_host is defined
    with_items: "{{ groups.all }}"

  - name: "Instalacion de paquetes: dnf"
    dnf:
      name: dnf
      state: latest
  
  - name: "dnf-plugins"
    dnf:
      name: dnf-plugins-core
      state: latest

  - name: "chrony"
    dnf:
      name: chrony
      state: latest

  - name: "nfs-utils"
    dnf:
      name: nfs-utils
      state: latest

  - name: "nfs4-acl-tools"
    dnf:
      name: nfs4-acl-tools
      state: latest

  - name: "wget"
    dnf:
      name: wget
      state: latest

  - name: "Desinstalacion de componentes sobrantes: docker podman"
    dnf:
      name: podman
      state: absent

  - name: "Iniciando servicio chrony"
    service:
      enabled: true
      name: "{{ item }}"
      state: started
    with_items:
      - chronyd
      - nfs-utils

  - name: "Desactivar modulo SELINUX"
    selinux:
      state: disabled