---

- name: "Instalacion de paquetes: nfs-utils"
  dnf:
    name: nfs-utils
    state: latest
-
  name: "Instalacion de paquetes: net-tools"
  dnf:
    name: net-tools
    state: latest

- name: "Creación de la ruta local de nfs (con max. privilegios)"
  file:
    path: /srv/nfs
    state: directory
    owner: Antonio
    group: Antonio
    mode: 0777
  
- name: Montar el directorio NFS 
  mount:
    fstype: nfs
    opts: defaults
    dump: 0
    passno: 0
    state: mounted
    src: "10.0.1.20:/srv/nfs"
    path: "/srv/nfs"

- name: Inicio del servicio de nfs
  systemd: 
    name: nfs-server
    state: started
    daemon_reload: yes
    enabled: yes

- name: Comprobar NFS OK
  shell: systemctl status nfs-server.service
  register: output 

- name: "Añadidos los host master y workers a exports"
  lineinfile:
    path: /etc/exports
    state: present
    line: "{{ item }}"
  with_items:
  - '/srv/nfs	10.0.1.10(rw,sync)'
  - '/srv/nfs	10.0.1.11(rw,sync)'
  - '/srv/nfs	10.0.1.12(rw,sync)'

- name: "Exportar el directorio que he creado: exportfs -r"
  command: exportfs -r

- name: "Exportar el directorio que he creado: exportfs -s"
  command: exportfs -s

- name: Iniciando firewall
  systemd:
    name: firewalld
    state: started
    enabled: yes
      
- name: Abriendo los puertos del firewall
  shell: |
    firewall-cmd --permanent --add-service=nfs
    firewall-cmd --permanent --add-service=rpc-bind
    firewall-cmd --permanent --add-service=mountd
    firewall-cmd --reload
  register: output 

- name: Aplicar configuracion del firewall
  shell: firewall-cmd --reload
