---
- hosts: all
  become: yes
  vars_files:
  - vars
  tasks:
  - name: Desactivando partición de swap
    shell: swapoff -a

  - name: Eliminando swap de la tabla de particiones /etc/fstab
    replace:
     path: /etc/fstab
     regexp: '(^/.*swap*)'
     replace: '# \1'

  - name: Configuración de IP de los nodos
    lineinfile:
      dest: /etc/hosts
      regexp: '.*{{ item }}$'
      line: "{{ hostvars[item].ansible_host }} {{item}}"
      state: present
    when: hostvars[item].ansible_host is defined
    with_items: "{{ groups.all }}"